export const SET_PROFILE = 'GET_PROFILE';
export const FETCH_MY_ALBUMS = 'FETCH_MY_ALBUMS';

export const SET_MY_SONGS = 'SET_MY_SONGS';
export const SET_SAVED_SONGS = 'SET_SAVED_SONGS';
export const SAVE_SONG = 'SAVE_SONG';

export const CHANGE_PROFILE_DESCRIPTION = 'CHANGE_PROFILE_DESCRIPTION';
export const CHANGE_PROFILE_NAME = 'CHANGE_PROFILE_NAME';